---
- hosts: demo
  become: True
  tasks:
    - name: Update Repo
      apt:
        update_cache: yes
        name: "*"
        state: present            
    - name: Install pip
      apt:
        name: pip
        state: present
    - name: Install docker
      apt:
        name: docker.io
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present        
    - name: Start the container
      docker_container:
        name: tomcatcontainer
        image: "manikandan27/newimage:'*'"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080


